In [ ]:
# Numpy -> Numerical Python
# Ndarray -> N dimensional array
# ndarray is the core data structure that NumPy provides for efficient numerical computation

In [1]:
# 1D array
import numpy as np

arr1 = np.array([1, 2, 3, 4, 5, 6])

print(type(arr1))

# 2D array

arr2 = np.array([[1, 2, 3], [3, 4, 5]])


# 3D array  (multiple 2d array)
arr3 = np.array([
    # 1st floor
    [ [1, 2, 3],
        [4, 5, 6] ],

    # 2nd floor
    [ [1, 2, 3],
        [4, 5, 6] ]
    ])



<class 'numpy.ndarray'>


In [17]:
# Array Attributes
# Dimention check

print(arr1.ndim)
print(arr2.ndim)
print(arr3.ndim)

# Shape
print(arr1.shape) # for 1D prints the number of element
print(arr2.shape) # for 2D prints the number of (row, col)
print(arr3.shape) # for 3D prints the number of (floor, row , col)

# Data type
print(arr1.dtype)
print(arr2.dtype)
print(arr3.dtype)

# Size
print(arr1.size)
print(arr2.size)
print(arr3.size)

1
2
3
(6,)
(2, 3)
(2, 2, 3)
int64
int64
int64
6
6
12


In [22]:
# ndarray data type

a = np.array([1, 2, 3])
print(a.dtype)

b = np.array([1.2, 5.6, 2.2])
print(b.dtype)

# upcasting (Here is 2 type of data. but all the data is stored as float to not loosing value)
c = np.array([1, 2, 3.5]) 
print(c.dtype)

d = np.array([2, 3, '4'])
print(d.dtype)  # U -> means string type

int64
float64
float64
<U21


In [26]:
# Selecting a datatype for an array

#way-1
e = np.array([1, 2, 3], dtype = np.int8) # -127<=int8<=127 , if any value is greater it over flows and give error
print(e.dtype)

# way-2

f = np.array([1,2,300])
print(f.dtype)
f = f.astype(np.int16)
print(f.dtype)

int8
int64
int16


In [40]:
# ndarray creation from existing data

lst = [10, 20, 30, 40, 55.6]

aa = np.array(lst)
print(aa)
print(type(aa))
print(aa.dtype)
print()

mixed_lst = [10, True, "Hello", 10.5]

bb = np.array(mixed_lst)
print(bb)
print(type(bb))
print(bb.dtype)
print()

matrix = np.array([[1, 2, 3], [3, 4, 5]])
cc = np.array(matrix)
print(cc)
print(type(cc))
print(cc.dtype)
print(cc.shape)
print(cc.ndim)
print()

# from tuple
tpl = (10, 20, 30)
dd = np.array(tpl)

print(dd)
print(type(dd))
print(dd.dtype)
print(dd.shape)
print(dd.ndim)
print()

# from set
st = {1,2,3}
ee = np.array(list(st))  # coverting to list is important other wise it become's a object

print(ee)
print(type(ee))
print(ee.dtype)
print(ee.shape)
print(ee.ndim)
print()

# Dictionary
dc = {'a':10, 'b':20, 'c':40}

keys = dc.keys()
values = dc.values()
items = dc.items()

 # keys to ndarray
ff = np.array(list(keys))  # coverting to list is important other wise it become's a object

print(ff)
print(type(ff))
print(ff.dtype)
print(ff.shape)
print(ff.ndim)
print()


 #Values to ndarray
gg = np.array(list(values))  # coverting to list is important other wise it become's a object

print(gg)
gg = gg.astype(np.int16)
print(type(gg))
print(gg.dtype)
print(gg.shape)
print(gg.ndim)
print()

  # items to ndarray
aaa = np.array(list(items))  # coverting to list is important other wise it become's a object

print(aaa)
print(type(aaa))
print(aaa.dtype)
print(aaa.shape)
print(aaa.ndim) # 2d array
print()

[10.  20.  30.  40.  55.6]
<class 'numpy.ndarray'>
float64

['10' 'True' 'Hello' '10.5']
<class 'numpy.ndarray'>
<U32

[[1 2 3]
 [3 4 5]]
<class 'numpy.ndarray'>
int64
(2, 3)
2

[10 20 30]
<class 'numpy.ndarray'>
int64
(3,)
1

[1 2 3]
<class 'numpy.ndarray'>
int64
(3,)
1

['a' 'b' 'c']
<class 'numpy.ndarray'>
<U1
(3,)
1

[10 20 40]
<class 'numpy.ndarray'>
int16
(3,)
1

[['a' '10']
 ['b' '20']
 ['c' '40']]
<class 'numpy.ndarray'>
<U21
(3, 2)
2



In [7]:
# ndarray creation from scratch

#np.zeros
bbb = np.zeros((2,3), dtype=np.int64) #(row, col)

print(bbb)
print(type(bbb))
print(bbb.dtype)
print(bbb.shape)
print(bbb.ndim)
print()

ccc = np.zeros_like(arr3)  # copying the shape and replace elements by zeros
print(ccc)
print(ccc.shape)
print()

[[0 0 0]
 [0 0 0]]
<class 'numpy.ndarray'>
int64
(2, 3)
2

[[[0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]]]
(2, 2, 3)



In [10]:
# np.ones

ddd = np.ones((3,4,3))

print(ddd)
print(type(ddd))
print(ddd.dtype)
print(ddd.shape)
print(ddd.ndim) # 3d array
print()

eee = np.ones_like(arr3)  # copying the shape and replace elements by one
print(eee)
print(eee.shape)
print()

[[[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]]
<class 'numpy.ndarray'>
float64
(3, 4, 3)
3

[[[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]]
(2, 2, 3)



In [37]:
# Empty array

fff = np.empty((2,2,2))  #Give random values

print(fff)
print(type(fff))
print(fff.dtype)
print(fff.shape)
print(fff.ndim) # 3d array
print()


ggg = np.empty_like(arr3)  # copying the shape and replace elements by random numbers
print(ggg)
print(ggg.shape)
print()

[[[0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]]]
<class 'numpy.ndarray'>
float64
(2, 2, 2)
3

[[[      1467824939848                  64                   0]
  [                  0                   0 4135209773570602594]]

 [[7076905864026993456 3559310669774927155 4134925919916931120]
  [3990525944625587046 3990813119775532129 3546128642804887865]]]
(2, 2, 3)



In [39]:
# np.full

hhh = np.full((4,3), 10)  # make same value array

print(hhh)
print(type(hhh))
print(hhh.dtype)
print(hhh.shape)
print(hhh.ndim)
print()


[[10 10 10]
 [10 10 10]
 [10 10 10]
 [10 10 10]]
<class 'numpy.ndarray'>
int64
(4, 3)
2



In [45]:
# Array genarator
# Arry creation with random values


iii = np.random.rand(3,3) # provides values within 0 to 1

print(iii)
print(type(iii))
print(iii.dtype)
print(iii.shape)
print(iii.ndim)
print()

#int

jjj = np.random.randint(1, 10, (3,3)) # (starting range, end of range, (row, col))

print(jjj)
print(type(jjj))
print(jjj.dtype)
print(jjj.shape)
print(jjj.ndim)
print()


# float

kkk = np.random.uniform(50,100, (3,3)) # provides values within 50 to 100

print(kkk)
print(type(kkk))
print(kkk.dtype)
print(kkk.shape)
print(kkk.ndim)
print()

[[0.68757982 0.95734894 0.71000286]
 [0.02986734 0.99954541 0.09514514]
 [0.10487789 0.41836221 0.74448515]]
<class 'numpy.ndarray'>
float64
(3, 3)
2

[[5 9 2]
 [4 9 2]
 [5 5 4]]
<class 'numpy.ndarray'>
int32
(3, 3)
2

[[63.46904051 73.67455721 57.85242231]
 [90.16784104 65.26592649 82.67525162]
 [98.62941127 73.25102392 63.51214504]]
<class 'numpy.ndarray'>
float64
(3, 3)
2



In [11]:
# np.arange(first, end, step)

aaaa = np.arange(0, 10, 1)

print(aaaa)
print(type(aaaa))
print(aaaa.dtype)
print(aaaa.shape)
print(aaaa.ndim)
print()

 # give shape
bbbb = np.arange(0, 9, 1).reshape(3,3)

print(bbbb)
print(type(bbbb))
print(bbbb.dtype)
print(bbbb.shape)
print(bbbb.ndim)
print()


[0 1 2 3 4 5 6 7 8 9]
<class 'numpy.ndarray'>
int64
(10,)
1

[[0 1 2]
 [3 4 5]
 [6 7 8]]
<class 'numpy.ndarray'>
int64
(3, 3)
2



In [12]:
# np.linespace.(start, end, koy bhag)

cccc = np.linspace(1, 10, 15) #-> from 1 to 15 is devided into 15 points equally

print(cccc)
print(type(cccc))
print(cccc.dtype)
print(cccc.shape)
print(cccc.ndim)
print()



[ 1.          1.64285714  2.28571429  2.92857143  3.57142857  4.21428571
  4.85714286  5.5         6.14285714  6.78571429  7.42857143  8.07142857
  8.71428571  9.35714286 10.        ]
<class 'numpy.ndarray'>
float64
(15,)
1



In [9]:
# np.logspace(start, end, koyta bhag a)

dddd = np.logspace(0,4,5) # to the powers will be within (start-end)

print(dddd)

dddd = np.logspace(0,4, 6, base=2)  # base are fixed and powers are divided in 6 parts how ot gives the result
print(dddd)


[1.e+00 1.e+01 1.e+02 1.e+03 1.e+04]
[ 1.          1.74110113  3.03143313  5.27803164  9.18958684 16.        ]


In [15]:
# Creating matrix for diagonal
# Diagonal matrix

diagonal_matrix = np.diag([1, 2, 3, 4])
print(diagonal_matrix)
print()

# identity matrix
identity_matrix = np.eye(4)  #-> 4x4, diagonal all element 1 and other zero
print(identity_matrix)
print()

mat = np.eye(3,4)  #-> (row, col)
print(mat)
print()

mat = np.eye(3,4, 1)  #-> (row, col, diagonal shifted)
print(mat)
print()

[[1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]
 [0 0 0 4]]

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]]

[[0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]



In [27]:
# indexing
print(arr1)
print(arr1[2])

print(arr2[0][1])

# 1D slicing
print(arr1[1:4])
print()

# 2D slicing -> arr[row_start : row_end : step, column_start : column_end : step]
row_0 = arr2[0:1,]
print(row_0)

row_1 = arr2[1:,]
print(row_1)
print()

col_0 = arr2[::,0:1]
print(col_0)

col_1 = arr2[::, 1:2]
print(col_1)

[1 2 3 4 5 6]
3
2
[2 3 4]

[[1 2 3]]
[[3 4 5]]

[[1]
 [3]]
[[2]
 [4]]


In [30]:
## Ndarray Copy Advanced Indexing and Iteration

print(arr1)

arr_mod = arr1[0:4].copy() # whithout using copy it stores the actual arrays location

arr_mod[2] = 200

print(arr_mod)

[1 2 3 4 5 6]
[  1   2 200   4]


In [40]:
# 1D
lst1 = np.array([10, 20, 30, 40])
values = lst1[[1,3]]
print(values) # printing the value of index 1 and 3

# 2D
print(arr2[[0,1],[1,2]]) # printing two index of 2d array. index (0,1) & (1,2)

# in boolean way
print(arr2[arr2>2])
print(arr2[arr2<2])

arr2[arr2>2] = 0
print(arr2)

[20 40]
[2 5]
[3 3 4 5]
[1]
[[1 2 0]
 [0 0 0]]


In [42]:
# iteration

ar = np.array([[10, 20, 30], [50, 60, 70]])

for i in np.nditer(ar): # using one loop printing a matrix not nested loop
    print(i)

10
20
30
50
60
70


In [7]:
# Practice

ab = map(int, input().split())

x = np.array(list(ab))

x = x*1.8 + 32

print(x)

 0 10 37 100 -10


[ 32.   50.   98.6 212.   14. ]
