In [1]:
import numpy as np

arr = np.random.randint(1, 100, size=(10, 5)) # size = (row, col)
print(arr.shape)

(10, 5)


In [15]:
# Change shape
x = arr.reshape(5,10)  # in reshape the total data num mustbe same to orginal

print(x.shape)
print(x.ndim)

(5, 10)
2


In [16]:
print(arr) 
print()

row_wise_flatten = arr.flatten()  # changed to 1 dim from 2 dim, sequence accordin row serial
print(row_wise_flatten)
print(row_wise_flatten.ndim)

col_wise_flatten = np.ravel(arr, order='F')  # 'F'-> col, 'C'-> row
print(col_wise_flatten)

[[ 8 15 62 88 21]
 [66 27 30 97 59]
 [75  8 84 26 71]
 [46 60 26  9 97]
 [25 19 14 55 44]
 [94 93 81 57 15]
 [86 29 36 78 36]
 [47 63 85 79 89]
 [44 31 40 68  4]
 [32  4 83 33 72]]

[ 8 15 62 88 21 66 27 30 97 59 75  8 84 26 71 46 60 26  9 97 25 19 14 55
 44 94 93 81 57 15 86 29 36 78 36 47 63 85 79 89 44 31 40 68  4 32  4 83
 33 72]
1
[ 8 66 75 46 25 94 86 47 44 32 15 27  8 60 19 93 29 63 31  4 62 30 84 26
 14 81 36 85 40 83 88 97 26  9 55 57 78 79 68 33 21 59 71 97 44 15 36 89
  4 72]


In [17]:
## Concatanation of 2 array

a = np.random.randint(10, 20, size=(2,3))
b = np.random.randint(20,30, size=(2,3))

print(a)
print()
print(b)
print()

con_row = np.concatenate((a,b), axis=0) # row wise
print(con_row)
print()
con_col = np.concatenate((a,b), axis=1) # column wise
print(con_col)


[[15 14 15]
 [12 17 15]]

[[24 29 26]
 [28 23 25]]

[[15 14 15]
 [12 17 15]
 [24 29 26]
 [28 23 25]]

[[15 14 15 24 29 26]
 [12 17 15 28 23 25]]


In [ ]:
# error 

# row wise concetanate korar shomoi column same thakbe 
# col wise concat korar shomoi row ta same thakte hobe 

x = np.random.randint(1 ,10 , size =(2,3))
y = np.random.randint(1 ,10 , size =(1,3))

r = np.concatenate((x,y),axis =0 )
r = np.concatenate((x,y),axis =1 )
print(r)

In [23]:
# Transpose

mat = np.array([[10,20, 30], [40, 50, 60]])

transpose = mat.T
print(transpose)

[[10 40]
 [20 50]
 [30 60]]


In [33]:
# array_split

c = np.random.randint(1,10, size=(10,))
print(c)

splited_array = np.array_split(c, 3) #(array, number of splits)

print(splited_array)

# splits equally, if not possible throw's error
# splt_array = np.split(c,3)

[9 5 5 2 8 8 3 3 2 2]
[array([9, 5, 5, 2], dtype=int32), array([8, 8, 3], dtype=int32), array([3, 2, 2], dtype=int32)]


In [36]:
# ndarray Arithmetic Operators

xx = np.array([10, 20, 30, 40, 50])
yy = np.array([1, 2, 3, 4, 5])

add = np.add(xx,yy) # xx + yy
print(add)

sub = xx - yy
print(sub)

mul = xx * yy
print(mul)

div = xx / yy
print(div)

mod = xx%yy
print(mod)

[11 22 33 44 55]
[ 9 18 27 36 45]
[ 10  40  90 160 250]
[10. 10. 10. 10. 10.]
[0 0 0 0 0]


In [50]:
# Mathematical function
# trigonometry

sin_val = np.sin(xx)  # defsultly prints redian values
print(sin_val)

cos_val = np.cos(xx)
print(cos_val)

# convert radian to degree value
deg_con = np.rad2deg(sin_val)
print(deg_con)
print()

# log
base_10_log_val = np.log10(xx) # mean's kon number 10 diye koybar bhag jay
print(base_10_log_val)

base_2_log_val = np.log2(xx)
print(base_2_log_val)
print()

# squre root
sqrt = np.sqrt(xx)
print(sqrt)
print()

# Total sum of a array
sm = sum(yy)
print(sm)
print()

# Cumulative_sum or prefix sum
cumul = np.cumulative_sum(xx)
print(cumul)

[-0.54402111  0.91294525 -0.98803162  0.74511316 -0.26237485]
[-0.83907153  0.40808206  0.15425145 -0.66693806  0.96496603]
[-31.17011362  52.30790979 -56.61004209  42.69183936 -15.03297177]

[1.         1.30103    1.47712125 1.60205999 1.69897   ]
[3.32192809 4.32192809 4.9068906  5.32192809 5.64385619]

[3.16227766 4.47213595 5.47722558 6.32455532 7.07106781]

15

[ 10  30  60 100 150]


In [6]:
# Broad casting
  # 1D
v = np.array([1, 2, 3, 4, 5])
ans = v + 2
print(ans)
print()

    # 2D
matrix = np.array([[5, 10 , 15, 20, 25], [3, 5, 7, 10, 13]])
result = matrix + 5
print(result)
print()

# If 1D and 2D have same size of column. they can be add
f = v + matrix
print(f)

[3 4 5 6 7]

[[10 15 20 25 30]
 [ 8 10 12 15 18]]

[[ 6 12 18 24 30]
 [ 4  7 10 14 18]]


In [12]:
# Numpy Logical Functions

# comparison - >,< , >= ,<= , == , !=

xxx = np.array([ 10 , 8 , 16 , 100 ])
yyy = np.array([ 2 , 3 ,16  ,5 ]) 

greater_than = xxx>yyy

print(greater_than)

equal = xxx==yyy 

print(equal) 

# all () -> if all true
# any() -> if at least one is true

print(np.all(greater_than)) 

print(np.any(equal))

[ True  True False  True]
[False False  True False]
False
True


In [21]:
# Sorting
    # In place sorting
z = np.array([10, 5, 8, 7, 2])

print(z)
z.sort()
print(z)
print()

    # Copy Sorting (main array is not changed)
l = np.array([2, 1, 9, 5, 7])
sort_arr = np.sort(l)
print(l)
print(sort_arr)

[10  5  8  7  2]
[ 2  5  7  8 10]

[2 1 9 5 7]
[1 2 5 7 9]


In [30]:
# 2D array sorting
ss = np.array([[50, 40, 10], [4, 5, 3]])
print(ss)
print()

    # Horizontal sorting
hor_sorting = np.sort(ss, axis=1)

print(hor_sorting)
print()

    # Vartical sorting
var_sorting = np.sort(ss, axis=0)

print(var_sorting)
print()

[[50 40 10]
 [ 4  5  3]]

[[10 40 50]
 [ 3  4  5]]

[[ 4  5  3]
 [50 40 10]]



In [33]:
# Finding element in array

index = np.where(z==5) # z is array
print(index)   # return's index

index = np.where(z>5)
print(index)

# Searching and replacing in array
    # np.where(condition, x, y), if true x, otherwise replace with y
index = np.where(z>5, z, 0)
print(index)   # return's array


(array([1]),)
(array([2, 3, 4]),)
[ 0  0  7  8 10]


In [40]:
# Searching in 2D array
print(ss)

index = np.where(ss>7) # returns 2 array 1st array contains rows index and 2nd array contains column's index
print(index)
print()

# Search max and min value of a array
z = np.array([10, 5, 8, 7, 10])
print(z)

max_val_indx = np.argmax(z)  # return's index (if multiple max returns the 1st one)
print(max_val_indx) 

min_val_indx = np.argmin(z) 
print(min_val_indx)

[[50 40 10]
 [ 4  5  3]]
(array([0, 0, 0]), array([0, 1, 2]))

[10  5  8  7 10]
0
1


In [49]:
# Counting in nd array
a = np.random.randint(1, 100, size=100)
print(a)
print()

value_greater_than_60 = np.count_nonzero(a>60)
print(value_greater_than_60)

value_equal_to_50 = np.count_nonzero(a==50)
print(value_equal_to_50)
print()

    #print each value's one time
unique_values = np.unique(a)
print(unique_values)
print()

    # Print's each element one time and returns it's count
unique_values_and_counts = np.unique(a, return_counts=True)
print(unique_values_and_counts)



[62 15 74 33 73 97  9 47 39 64 25 42 36 29 19 50 62 96 24 69  3 99 77 81
 89 30 78 57 94 96 52 18 17 87 57 47  8 75 25 98 51 20 63 26 60 36 58 49
 95 45  4 75 27 70 50 77 39 97 25 48 60 30 71 51 37 47 44  9 90 15 94 33
 68 55 33 30 84 28 58  4 37 18 61 29 84 83 72 75  1 77 48 78 13 14 15 56
 50 98 39 96]

38
3

[ 1  3  4  8  9 13 14 15 17 18 19 20 24 25 26 27 28 29 30 33 36 37 39 42
 44 45 47 48 49 50 51 52 55 56 57 58 60 61 62 63 64 68 69 70 71 72 73 74
 75 77 78 81 83 84 87 89 90 94 95 96 97 98 99]

(array([ 1,  3,  4,  8,  9, 13, 14, 15, 17, 18, 19, 20, 24, 25, 26, 27, 28,
       29, 30, 33, 36, 37, 39, 42, 44, 45, 47, 48, 49, 50, 51, 52, 55, 56,
       57, 58, 60, 61, 62, 63, 64, 68, 69, 70, 71, 72, 73, 74, 75, 77, 78,
       81, 83, 84, 87, 89, 90, 94, 95, 96, 97, 98, 99], dtype=int32), array([1, 1, 2, 1, 2, 1, 1, 3, 1, 2, 1, 1, 1, 3, 1, 1, 1, 2, 3, 3, 2, 2,
       3, 1, 1, 1, 3, 2, 1, 3, 2, 1, 1, 1, 2, 2, 2, 1, 2, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 3, 3, 2, 1, 1, 2, 1, 1, 1, 2, 1,

In [1]:
# Write in CSV file
import csv

# Data for each row
rows = [
    [78, 85, 82],
    [56, 67, 72],
    [89, 92, 88],
    [45, 52, 58],
    [70, 75, 80],
    [92, 90, 91],
    [61, 70, 62],
    [55, 57, 54],
    [88, 85, 87],
    [74, 70, 76],
    [66, 69, 68],
    [80, 64, 81],
    [49, 82, 60],
    [73, 78, 74],
    [59, 74, 71],
    [68, 71, 79],
    [77, 79, 73],
    [74, 83, 85],
    [62, 65, 63],
    [95, 97, 96]
]

# Header
header = ['Math', 'Science', 'English']

# Write to CSV
with open('student_scores.csv', 'w', newline='') as file:
    writer = csv.writer(file)
    writer.writerow(header)
    writer.writerows(rows)

print("CSV file written successfully!")



CSV file written successfully!


In [2]:
# Statistical function
    # Data Load
data = np.genfromtxt('student_scores.csv', delimiter=',', skip_header=1)
print(data)

[[78. 85. 82.]
 [56. 67. 72.]
 [89. 92. 88.]
 [45. 52. 58.]
 [70. 75. 80.]
 [92. 90. 91.]
 [61. 70. 62.]
 [55. 57. 54.]
 [88. 85. 87.]
 [74. 70. 76.]
 [66. 69. 68.]
 [80. 64. 81.]
 [49. 82. 60.]
 [73. 78. 74.]
 [59. 74. 71.]
 [68. 71. 79.]
 [77. 79. 73.]
 [74. 83. 85.]
 [62. 65. 63.]
 [95. 97. 96.]]


In [9]:
    # Column wise values
math_marks = data[::, :1]
print(math_marks.T)

max_math_marks = np.max(math_marks)
print(max_math_marks)
min_math_marks = np.min(math_marks)
print(min_math_marks)

average_math_marks = np.mean(math_marks)
print(average_math_marks)

median_math_marks = np.median(math_marks)
print(median_math_marks)

[[78. 56. 89. 45. 70. 92. 61. 55. 88. 74. 66. 80. 49. 73. 59. 68. 77. 74.
  62. 95.]]
95.0
45.0
70.55
71.5


In [10]:
    # correlation
study_hours = np.array([2, 4, 5, 7, 8])
exam_scores = np.array([65, 75, 78, 88, 92])

data = np.array([study_hours, exam_scores])

correlation = np.corrcoef(data)

print("Correlation Matrix:\n", correlation)

Correlation Matrix:
 [[1.         0.99859154]
 [0.99859154 1.        ]]


In [22]:
## Linear Algebra

A = np.array([[1, 2, 3],
            [4, 5, 6]])

B = np.array([[7, 8],
             [9, 10],
             [11, 12]])

dot_product = np.dot(A, B)
print(dot_product)

# Trace (sum of primary diagonal elements of array)
tr = np.trace(A) #(5+1)
print(tr)

# Determinent
sq_mat = np.array([[1, 2, 3],
                   [4, 5, 6], 
                   [7, 8, 9]
                  ])

det_of_sq_mat = np.linalg.det(sq_mat)
rank_sq = np.linalg.matrix_rank(sq_mat)
print(det_of_sq_mat)
print(rank_sq)

[[ 58  64]
 [139 154]]
6
-9.51619735392994e-16
2
