In [1]:
#1
import numpy as np

arr1 = np.array([1, 2, 3, 4])
arr2 = np.array([[10, 20, 30],
                 [40, 50, 60]])
arr3 = np.array([
                [ [10, 20, 30], 
                 [40, 50, 60] ], 
    
                 [ [70, 80, 90],
                  [100, 110, 120] ], 
    
                 [ [130, 140, 150], 
                  [160, 170, 180] ]
                ])

print(arr1.ndim, arr1.shape, arr1.size)
print(arr2.ndim, arr2.shape, arr2.size)
print(arr3.ndim, arr3.shape, arr3.size)

1 (4,) 4
2 (2, 3) 6
3 (3, 2, 3) 18


In [18]:
#2
array_zero = np.zeros((3,3))
array_one = np.ones((2,5))
arr = np.full((3,3),7)

print(array_zero)
print()
print(array_one)
print()
print(arr)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]

[[7 7 7]
 [7 7 7]
 [7 7 7]]


In [6]:
#3
a = np.random.randint(10, 50, size=(6,))
print(a)

b = np.linspace(10, 50, 6)
print(b)

c = np.logspace(10, 50, 5)
print(c)

[37 11 29 20 18 22]
[10. 18. 26. 34. 42. 50.]
[1.e+10 1.e+20 1.e+30 1.e+40 1.e+50]


In [14]:
#4
d = np.random.randint(1, 15, size=(4,4))
print(d)
print()

first_row = d[:1,]
print(first_row)
print()

last_col = d[::, 3:]
print(last_col)
print()

sub_ar = d[1:3,1:3]
print(sub_ar)

[[ 9  5  7  3]
 [ 3  2  3  1]
 [ 4 11  9  6]
 [ 5  1 13  8]]

[[9 5 7 3]]

[[3]
 [1]
 [6]
 [8]]

[[ 2  3]
 [11  9]]


In [15]:
#5
e = np.array([1, 2, 3])

f = np.ones((3,3))
sm = sum(e)

f = f + sm

print(f)


[[7. 7. 7.]
 [7. 7. 7.]
 [7. 7. 7.]]


In [17]:
# 6

A = np.random.randint(1,10, size=(3,3))
B = np.random.randint(1,10, size=(3,3))
print(A)
print()
print(B)
print()

result = (A+B)/2
ans = (A**2) + (B**2)

print(result)
print()
print(ans)

[[4 8 7]
 [3 2 4]
 [8 8 5]]

[[5 5 7]
 [7 7 3]
 [4 8 4]]

[[4.5 6.5 7. ]
 [5.  4.5 3.5]
 [6.  8.  4.5]]

[[ 41  89  98]
 [ 58  53  25]
 [ 80 128  41]]
